### ISSUE TITLE
Compile errors - help please

### ISSUE THREAD

**Issue by leisztom** [lucbloom/unity_image_with_hit_detection_on_shape#2]
Assets/MusicLabe/ImageWithHitDetectionOnShape.cs(128,8): error CS0103: The name 'Vec' does not exist in the current context

Assets/MusicLabe/ImageWithHitDetectionOnShape.cs(126,29): error CS1061: 'Vector3' does not contain a definition for 'xy' and no accessible extension method 'xy' accepting a first argument of type 'Vector3' could be found (are you missing a using directive or an assembly reference?)

Assets/MusicLabe/ImageWithHitDetectionOnShape.cs(127,27): error CS1061: 'Vector3' does not contain a definition for 'xy' and no accessible extension method 'xy' accepting a first argument of type 'Vector3' could be found (are you missing a using directive or an assembly reference?)

Assets/MusicLabe/ImageWithHitDetectionOnShape.cs(128,8): error CS0103: The name 'Vec' does not exist in the current context

**Comment by lucbloom** [comment]
These are indeed some Vector2 utility functions. Vec.xy creates a new Vector2 of a Vector3 or with the supplied parameters.
I've adjusted the code for you.

**Comment by leisztom** [comment]
Great! Thank you!
